---
- name: Subscription manager RedHat
  hosts: jmeternodes
  become: true

  vars:
    subscription_username: "faloppaalessio"
    subscription_password: "7cXYuWw4$VVCkzk"

  tasks:
  - name: register with sm
    community.general.redhat_subscription:
      state: present
      username: "{{ subscription_username }}"
      password: "{{ subscription_password }}"
      auto_attach: true
